[build]
  publish = "public"
  command = "pip install pandas pyyaml && python3 excel_pipeline.py && hugo --minify"

[context.production.environment]
  HUGO_VERSION = "0.154.5"
  HUGO_ENV = "production"
